import base64
import tempfile
import os
from fpdf import FPDF
from datetime import datetime

class CardioGuardPDF(FPDF):
    def header(self):
        # Main Title
        self.set_font("Arial", "B", 20)
        self.set_text_color(21, 26, 35)
        self.cell(0, 10, "CardioGuard Clinical AI Report", border=0, ln=1, align="C")
        
        # University Branding
        self.set_font("Arial", "B", 12)
        self.set_text_color(129, 140, 248) # Brand Blue Color
        self.cell(0, 8, "QUAID-I-AZAM UNIVERSITY ISLAMABAD", border=0, ln=1, align="C")
        self.line(10, 30, 200, 30)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 9)
        self.set_text_color(156, 163, 175)
        self.cell(0, 10, f"Page {self.page_no()} | System Developer: HARIS ATTIQUE", border=0, align="C")

def generate_pdf_base64(user_profile: dict, ai_output: dict, total_events: int) -> str:
    pdf = CardioGuardPDF()
    pdf.add_page()

    # Get Current Date and Time
    current_date = datetime.now().strftime("%B %d, %Y - %I:%M %p")

    # 1. Patient Details Section
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Patient Profile", ln=1)
    
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 6, f"Date Generated: {current_date}", ln=1)
    pdf.cell(0, 6, f"Name: {user_profile.get('full_name', 'N/A')}", ln=1)
    pdf.cell(0, 6, f"Age: {user_profile.get('age', 'N/A')} | Weight: {user_profile.get('weight', 'N/A')} kg | Blood Type: {user_profile.get('blood_type', 'N/A')}", ln=1)
    pdf.cell(0, 6, f"Total Alerts Analyzed (Last 30 Days): {total_events}", ln=1)
    pdf.ln(10)

    # 2. AI Risk Assessment Section
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Cardiac Risk Assessment", ln=1)

    risk_level = ai_output.get("risk_level", "Unknown")
    risk_score = ai_output.get("risk_score_percentage", 0)
    
    # Dynamic Colors for Risk Level
    if risk_level.upper() in ["HIGH", "CRITICAL"]:
        pdf.set_text_color(220, 38, 38) # Red
    elif risk_level.upper() == "MODERATE":
        pdf.set_text_color(202, 138, 4) # Yellow
    else:
        pdf.set_text_color(22, 163, 74) # Green

    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, f"Risk Level: {risk_level.upper()} ({risk_score}% Risk Score)", ln=1)
    
    # 3. Clinical Summary
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", "B", 12)
    pdf.ln(5)
    pdf.cell(0, 8, "Clinical Summary:", ln=1)
    pdf.set_font("Arial", "", 11)
    pdf.multi_cell(0, 6, ai_output.get("clinical_summary", "No summary provided."))
    pdf.ln(10)

    # 4. Actionable Recommendations
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Recommendations:", ln=1)
    pdf.set_font("Arial", "", 11)
    for rec in ai_output.get("recommendations", []):
        pdf.multi_cell(0, 6, f"- {rec}")
    
    # 5. Medical Disclaimer
    pdf.ln(15) # Add some space before the disclaimer
    pdf.set_font("Arial", "I", 10)
    pdf.set_text_color(128, 128, 128) # Gray color for disclaimer
    disclaimer_text = "Disclaimer: This report is generated by an AI system for informational purposes only and is not a substitute for professional medical advice, diagnosis, or treatment. Please consult a qualified healthcare provider."
    pdf.multi_cell(0, 5, disclaimer_text)
    
    # Generate PDF to a temporary file and convert to Base64
    temp_filepath = os.path.join(tempfile.gettempdir(), f"report_{datetime.now().timestamp()}.pdf")
    pdf.output(temp_filepath)

    with open(temp_filepath, "rb") as pdf_file:
        encoded_string = base64.b64encode(pdf_file.read()).decode('utf-8')
    
    # Clean up temp file
    os.remove(temp_filepath)
    
    return encoded_string